fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    staging: "https://github.com/voxpupuli/puppet-staging.git"
    concat: "https://github.com/puppetlabs/puppet-concat.git"
  symlinks:
    consul_template: "#{source_dir}"
