---
language: ruby
bundler_args: --without development system_tests
before_install:
  - rm Gemfile.lock || true
  - gem install bundler
sudo: false
cache: bundler
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
script: bundle exec rake test
env:
  - PUPPET_VERSION="~> 3.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
  - PUPPET_VERSION="~> 4.0"
matrix:
  exclude:
  - rvm: 1.8.7
    env: PUPPET_VERSION="~> 4.0"
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 4.0"
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 4.0"
